import type { Metadata } from 'next'
//import localFont from 'next/font/local'
import './globals.css'
import '@/styles/style.scss'
import Header from '@/components/globals/header'
import Footer from '@/components/globals/footer'
import SmoothScroll from '@/globals/hooks/smoothScroll'

/*const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-gezist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
}) */

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link href="/favicon.ico" rel="icon" sizes="32x32" />
      </head>
      <body className="antialiased">
        <Header />
        <SmoothScroll />
        {children}
        <Footer />
      </body>
    </html>
  )
}
