/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accordions".
 */
export type Accordions =
  | {
      title?: string | null;
      body?: string | null;
      linkLabel?: string | null;
      linkType?: ('internal' | 'custom') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
      image?: (number | null) | Media;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    categories: Category;
    productCollections: ProductCollection;
    scooters: Scooter;
    chairs: Chair;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    productCollections: ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    scooters: ScootersSelect<false> | ScootersSelect<true>;
    chairs: ChairsSelect<false> | ChairsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  pageTitle: string;
  slug: string;
  layout?:
    | (
        | HeroBlock
        | CalltoActionBlock
        | RichText
        | FaqBlock
        | FeaturesBlock
        | GridCardsBlock
        | QuoteBlock
        | LogosBlock
        | ExploreProducts
        | CoverBanner
        | FeatureColumns
        | FeatureAccordion
        | ReviewsCarousel
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heroHeading?: string | null;
  heroText?: string | null;
  heroImage?: (number | Media)[] | null;
  heroButtons?: Buttons;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Buttons".
 */
export interface Buttons {
  primaryLabel?: string | null;
  primaryLink?: string | null;
  secondaryLabel?: string | null;
  secondaryLink?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalltoActionBlock".
 */
export interface CalltoActionBlock {
  ctaHeading?: string | null;
  ctaText?: string | null;
  ctaButtons?: Buttons;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichText".
 */
export interface RichText {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RichText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  faqHeading?: string | null;
  faqText?: string | null;
  faqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  featuresHeading?: string | null;
  featuresText?: string | null;
  features?:
    | {
        featureIcon?: (number | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridCardsBlock".
 */
export interface GridCardsBlock {
  gridCardsHeading?: string | null;
  gridCardsText?: string | null;
  gridcards?:
    | {
        image?: (number | null) | Media;
        title?: string | null;
        link?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'GridCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quoteHeading?: string | null;
  quoteText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  logosHeading?: string | null;
  logosText?: string | null;
  logos?:
    | {
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExploreProducts".
 */
export interface ExploreProducts {
  subheading?: string | null;
  heading?: string | null;
  products?:
    | {
        collection?: {
          relationTo: 'productCollections';
          value: number | ProductCollection;
        } | null;
        image?: (number | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ExploreProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCollections".
 */
export interface ProductCollection {
  id: number;
  collectionTitle: string;
  slug: string;
  layout?: HeroBlock[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverBanner".
 */
export interface CoverBanner {
  backgroundImage?: (number | null) | Media;
  content?: {
    logo?: (number | null) | Media;
    heading?: string | null;
    body?: string | null;
    bottomLogos?: {
      body?: string | null;
      logos?:
        | {
            logo?: (number | null) | Media;
            id?: string | null;
          }[]
        | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'CoverBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureColumns".
 */
export interface FeatureColumns {
  features?:
    | {
        icon?: string | null;
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeatureColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordion".
 */
export interface FeatureAccordion {
  heading?: string | null;
  body?: string | null;
  accordions?: Accordions;
  button?: {
    label?: string | null;
    linkLabel?: string | null;
    linkType?: ('internal' | 'custom') | null;
    page?: (number | null) | Page;
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeatureAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsCarousel".
 */
export interface ReviewsCarousel {
  content?: {
    heading?: string | null;
    body?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ReviewsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scooters".
 */
export interface Scooter {
  id: number;
  productName: string;
  slug: string;
  layout?:
    | (
        | ProductHero
        | ProductIntro
        | KeyFeatures
        | FeaturesGrid
        | OverlayBanner
        | CardGrid
        | SpecificationsBlock
        | FeatureAccordion
        | CustomerPhotographs
        | ImageHotspots
      )[]
    | null;
  names?: NameVariations;
  menuDesc?: string | null;
  category?: (number | null) | Category;
  mediaGallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  productCutout?: (number | null) | Media;
  sliderImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  productResources?:
    | {
        title?: string | null;
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  hero?: Hero;
  specs: Specifications;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductHero".
 */
export interface ProductHero {
  heroContent?: {
    heading?: string | null;
    body?: string | null;
    list?:
      | {
          listItem?: string | null;
          id?: string | null;
        }[]
      | null;
    buttons?:
      | {
          link?: {
            linkType?: ('internal' | 'custom') | null;
            newTab?: ('default' | 'newTab') | null;
            linkLabel?: string | null;
            page?: (number | null) | Page;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  heroImages?: {
    images?: (number | Media)[] | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ProductHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductIntro".
 */
export interface ProductIntro {
  content?: {
    useIcon?: ('icon' | 'noIcon') | null;
    heading?: string | null;
    body?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ProductIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyFeatures".
 */
export interface KeyFeatures {
  content?: {
    heading?: string | null;
    features?:
      | {
          heading?: string | null;
          body?: string | null;
          icon?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'KeyFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGrid".
 */
export interface FeaturesGrid {
  sectionHeading?: {
    heading?: string | null;
    buttons?:
      | {
          link?: {
            linkType?: ('internal' | 'custom') | null;
            newTab?: ('default' | 'newTab') | null;
            linkLabel?: string | null;
            page?: (number | null) | Page;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  features?:
    | {
        image?: (number | null) | Media;
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeaturesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OverlayBanner".
 */
export interface OverlayBanner {
  content?: {
    heading?: string | null;
    body?: string | null;
  };
  backgroundImage?: {
    image?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'OverlayBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGrid".
 */
export interface CardGrid {
  heading?: string | null;
  body?: string | null;
  cardGrid?:
    | {
        image?: (number | null) | Media;
        title?: string | null;
        text?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecificationsBlock".
 */
export interface SpecificationsBlock {
  content?: {
    heading?: string | null;
    body?: string | null;
    includeSwitch?: ('switch' | 'disable') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'SpecificationsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerPhotographs".
 */
export interface CustomerPhotographs {
  content?: {
    heading?: string | null;
    body?: string | null;
    buttons?:
      | {
          link?: {
            linkType?: ('internal' | 'custom') | null;
            newTab?: ('default' | 'newTab') | null;
            linkLabel?: string | null;
            page?: (number | null) | Page;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  images?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CustomerPhotographs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageHotspots".
 */
export interface ImageHotspots {
  content?: {
    heading?: string | null;
    body?: string | null;
  };
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageHotspots';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NameVariations".
 */
export interface NameVariations {
  shortName?: string | null;
  shortNameSimple?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  title?: string | null;
  subtitle?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Specifications".
 */
export interface Specifications {
  stats: {
    maxSpeed: {
      value: number;
      unit?: ('mph' | 'kph') | null;
    };
    maxRange: {
      value: number;
      unit?: ('miles' | 'kilometers') | null;
    };
    maxUserWeight: {
      stone: number;
      lbs: number;
    };
    scooterWeight: {
      stone: number;
      lbs: number;
    };
    battery: {
      value: number;
      unit?: 'Ah Lith.' | null;
    };
    fixedLights?: ('yes' | 'no') | null;
    offBoardCharging?: ('yes' | 'no') | null;
    suspension?: ('yes' | 'no') | null;
    maxSlope?: {
      value?: number | null;
      unit?: string | null;
    };
    turningRadius?: {
      value?: number | null;
      unit?: ('mm' | 'in') | null;
    };
    tyreType?: string | null;
  };
  dimensions?: {
    totalLength?: number | null;
    totalWidth?: number | null;
    totalHeight?: number | null;
    foldedHeight?: number | null;
    seatWidth?: number | null;
    seatDepth?: number | null;
    backrestHeight?: number | null;
    handlebarWidth?: number | null;
    groundClearance?: number | null;
    frontWheelDiameter?: number | null;
    rearWheelDiameter?: number | null;
  };
  protection?: {
    insurance?: string | null;
    warranty?: string | null;
  };
  promotional?: {
    tradeIn?: string | null;
    finance?: string | null;
  };
  finishes?: {
    finish?: string | null;
  };
  /**
   * Use this for any additional stats to show in the top line stats section
   */
  extraStats?:
    | {
        name: string;
        value: string;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairs".
 */
export interface Chair {
  id: number;
  productName: string;
  slug: string;
  names?: NameVariations;
  menuDesc?: string | null;
  category?: (number | null) | Category;
  mediaGallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  productCutout?: (number | null) | Media;
  sliderImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  productResources?:
    | {
        title?: string | null;
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  hero?: Hero;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'productCollections';
        value: number | ProductCollection;
      } | null)
    | ({
        relationTo: 'scooters';
        value: number | Scooter;
      } | null)
    | ({
        relationTo: 'chairs';
        value: number | Chair;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageTitle?: T;
  slug?: T;
  layout?:
    | T
    | {
        Hero?: T | HeroBlockSelect<T>;
        Cta?: T | CalltoActionBlockSelect<T>;
        RichText?: T | RichTextSelect<T>;
        Faq?: T | FaqBlockSelect<T>;
        Features?: T | FeaturesBlockSelect<T>;
        GridCards?: T | GridCardsBlockSelect<T>;
        Quote?: T | QuoteBlockSelect<T>;
        Logos?: T | LogosBlockSelect<T>;
        ExploreProducts?: T | ExploreProductsSelect<T>;
        CoverBanner?: T | CoverBannerSelect<T>;
        FeatureColumns?: T | FeatureColumnsSelect<T>;
        FeatureAccordion?: T | FeatureAccordionSelect<T>;
        ReviewsCarousel?: T | ReviewsCarouselSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heroHeading?: T;
  heroText?: T;
  heroImage?: T;
  heroButtons?: T | ButtonsSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Buttons_select".
 */
export interface ButtonsSelect<T extends boolean = true> {
  primaryLabel?: T;
  primaryLink?: T;
  secondaryLabel?: T;
  secondaryLink?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalltoActionBlock_select".
 */
export interface CalltoActionBlockSelect<T extends boolean = true> {
  ctaHeading?: T;
  ctaText?: T;
  ctaButtons?: T | ButtonsSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichText_select".
 */
export interface RichTextSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  faqHeading?: T;
  faqText?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  featuresHeading?: T;
  featuresText?: T;
  features?:
    | T
    | {
        featureIcon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridCardsBlock_select".
 */
export interface GridCardsBlockSelect<T extends boolean = true> {
  gridCardsHeading?: T;
  gridCardsText?: T;
  gridcards?:
    | T
    | {
        image?: T;
        title?: T;
        link?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quoteHeading?: T;
  quoteText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  logosHeading?: T;
  logosText?: T;
  logos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExploreProducts_select".
 */
export interface ExploreProductsSelect<T extends boolean = true> {
  subheading?: T;
  heading?: T;
  products?:
    | T
    | {
        collection?: T;
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverBanner_select".
 */
export interface CoverBannerSelect<T extends boolean = true> {
  backgroundImage?: T;
  content?:
    | T
    | {
        logo?: T;
        heading?: T;
        body?: T;
        bottomLogos?:
          | T
          | {
              body?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureColumns_select".
 */
export interface FeatureColumnsSelect<T extends boolean = true> {
  features?:
    | T
    | {
        icon?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordion_select".
 */
export interface FeatureAccordionSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  accordions?: T | AccordionsSelect<T>;
  button?:
    | T
    | {
        label?: T;
        linkLabel?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accordions_select".
 */
export interface AccordionsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  linkLabel?: T;
  linkType?: T;
  page?: T;
  url?: T;
  newTab?: T;
  image?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsCarousel_select".
 */
export interface ReviewsCarouselSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCollections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  collectionTitle?: T;
  slug?: T;
  layout?:
    | T
    | {
        Hero?: T | HeroBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scooters_select".
 */
export interface ScootersSelect<T extends boolean = true> {
  productName?: T;
  slug?: T;
  layout?:
    | T
    | {
        ProductHero?: T | ProductHeroSelect<T>;
        ProductIntro?: T | ProductIntroSelect<T>;
        KeyFeatures?: T | KeyFeaturesSelect<T>;
        FeaturesGrid?: T | FeaturesGridSelect<T>;
        OverlayBanner?: T | OverlayBannerSelect<T>;
        CardGrid?: T | CardGridSelect<T>;
        SpecificationsBlock?: T | SpecificationsBlockSelect<T>;
        FeatureAccordion?: T | FeatureAccordionSelect<T>;
        CustomerPhotographs?: T | CustomerPhotographsSelect<T>;
        ImageHotspots?: T | ImageHotspotsSelect<T>;
      };
  names?: T | NameVariationsSelect<T>;
  menuDesc?: T;
  category?: T;
  mediaGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  productCutout?: T;
  sliderImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  productResources?:
    | T
    | {
        title?: T;
        image?: T;
        caption?: T;
        id?: T;
      };
  hero?: T | HeroSelect<T>;
  specs?: T | SpecificationsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductHero_select".
 */
export interface ProductHeroSelect<T extends boolean = true> {
  heroContent?:
    | T
    | {
        heading?: T;
        body?: T;
        list?:
          | T
          | {
              listItem?: T;
              id?: T;
            };
        buttons?:
          | T
          | {
              link?:
                | T
                | {
                    linkType?: T;
                    newTab?: T;
                    linkLabel?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  heroImages?:
    | T
    | {
        images?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductIntro_select".
 */
export interface ProductIntroSelect<T extends boolean = true> {
  content?:
    | T
    | {
        useIcon?: T;
        heading?: T;
        body?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyFeatures_select".
 */
export interface KeyFeaturesSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        features?:
          | T
          | {
              heading?: T;
              body?: T;
              icon?: T;
              image?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGrid_select".
 */
export interface FeaturesGridSelect<T extends boolean = true> {
  sectionHeading?:
    | T
    | {
        heading?: T;
        buttons?:
          | T
          | {
              link?:
                | T
                | {
                    linkType?: T;
                    newTab?: T;
                    linkLabel?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  features?:
    | T
    | {
        image?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OverlayBanner_select".
 */
export interface OverlayBannerSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  backgroundImage?:
    | T
    | {
        image?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGrid_select".
 */
export interface CardGridSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  cardGrid?:
    | T
    | {
        image?: T;
        title?: T;
        text?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecificationsBlock_select".
 */
export interface SpecificationsBlockSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        body?: T;
        includeSwitch?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerPhotographs_select".
 */
export interface CustomerPhotographsSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        body?: T;
        buttons?:
          | T
          | {
              link?:
                | T
                | {
                    linkType?: T;
                    newTab?: T;
                    linkLabel?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageHotspots_select".
 */
export interface ImageHotspotsSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NameVariations_select".
 */
export interface NameVariationsSelect<T extends boolean = true> {
  shortName?: T;
  shortNameSimple?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Specifications_select".
 */
export interface SpecificationsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        maxSpeed?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        maxRange?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        maxUserWeight?:
          | T
          | {
              stone?: T;
              lbs?: T;
            };
        scooterWeight?:
          | T
          | {
              stone?: T;
              lbs?: T;
            };
        battery?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        fixedLights?: T;
        offBoardCharging?: T;
        suspension?: T;
        maxSlope?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        turningRadius?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        tyreType?: T;
      };
  dimensions?:
    | T
    | {
        totalLength?: T;
        totalWidth?: T;
        totalHeight?: T;
        foldedHeight?: T;
        seatWidth?: T;
        seatDepth?: T;
        backrestHeight?: T;
        handlebarWidth?: T;
        groundClearance?: T;
        frontWheelDiameter?: T;
        rearWheelDiameter?: T;
      };
  protection?:
    | T
    | {
        insurance?: T;
        warranty?: T;
      };
  promotional?:
    | T
    | {
        tradeIn?: T;
        finance?: T;
      };
  finishes?:
    | T
    | {
        finish?: T;
      };
  extraStats?:
    | T
    | {
        name?: T;
        value?: T;
        suffix?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairs_select".
 */
export interface ChairsSelect<T extends boolean = true> {
  productName?: T;
  slug?: T;
  names?: T | NameVariationsSelect<T>;
  menuDesc?: T;
  category?: T;
  mediaGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  productCutout?: T;
  sliderImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  productResources?:
    | T
    | {
        title?: T;
        image?: T;
        caption?: T;
        id?: T;
      };
  hero?: T | HeroSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  items?:
    | {
        label: string;
        hasDropdown?: boolean | null;
        linkLabel?: string | null;
        linkType?: ('internal' | 'custom') | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        /**
         * Pick a submenu type. More types (Blog, Contact) coming.
         */
        submenu?:
          | (
              | {
                  viewAll: {
                    image?: (number | null) | Media;
                    title: string;
                    description?: string | null;
                    linkLabel?: string | null;
                    linkType?: ('internal' | 'custom') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    newTab?: boolean | null;
                  };
                  products?:
                    | (
                        | {
                            relationTo: 'scooters';
                            value: number | Scooter;
                          }
                        | {
                            relationTo: 'chairs';
                            value: number | Chair;
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'productSubmenu';
                }
              | {
                  link: {
                    image?: (number | null) | Media;
                    title: string;
                    description?: string | null;
                    linkLabel?: string | null;
                    linkType?: ('internal' | 'custom') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    newTab?: boolean | null;
                  };
                  linkList?:
                    | {
                        icon?: string | null;
                        title: string;
                        linkLabel?: string | null;
                        linkType?: ('internal' | 'custom') | null;
                        page?: (number | null) | Page;
                        url?: string | null;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'genericSubmenu';
                }
              | {
                  linkList?:
                    | {
                        icon?: string | null;
                        title: string;
                        linkLabel?: string | null;
                        linkType?: ('internal' | 'custom') | null;
                        page?: (number | null) | Page;
                        url?: string | null;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  pullOutLink: {
                    image?: (number | null) | Media;
                    title: string;
                    description?: string | null;
                    linkLabel?: string | null;
                    linkType?: ('internal' | 'custom') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    newTab?: boolean | null;
                  };
                  body?: {
                    heading?: string | null;
                    content?: {
                      root: {
                        type: string;
                        children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    } | null;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contactSubmenu';
                }
              | {
                  linkList?:
                    | {
                        icon?: string | null;
                        title: string;
                        linkLabel?: string | null;
                        linkType?: ('internal' | 'custom') | null;
                        page?: (number | null) | Page;
                        url?: string | null;
                        newTab?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  articles?: {
                    heading?: string | null;
                    /**
                     * How many of the most recent articles to show.
                     */
                    limit?: number | null;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'resourceSubmenu';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  primaryButtonLabel?: string | null;
  primaryButtonLink?: string | null;
  secondaryButtonLabel?: string | null;
  secondaryButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footerNavigation?:
    | {
        links?:
          | {
              label?: string | null;
              linkLabel?: string | null;
              linkType?: ('internal' | 'custom') | null;
              page?: (number | null) | Page;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  copyrightNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  items?:
    | T
    | {
        label?: T;
        hasDropdown?: T;
        linkLabel?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
        submenu?:
          | T
          | {
              productSubmenu?:
                | T
                | {
                    viewAll?:
                      | T
                      | {
                          image?: T;
                          title?: T;
                          description?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                        };
                    products?: T;
                    id?: T;
                    blockName?: T;
                  };
              genericSubmenu?:
                | T
                | {
                    link?:
                      | T
                      | {
                          image?: T;
                          title?: T;
                          description?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                        };
                    linkList?:
                      | T
                      | {
                          icon?: T;
                          title?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              contactSubmenu?:
                | T
                | {
                    linkList?:
                      | T
                      | {
                          icon?: T;
                          title?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                          id?: T;
                        };
                    pullOutLink?:
                      | T
                      | {
                          image?: T;
                          title?: T;
                          description?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                        };
                    body?:
                      | T
                      | {
                          heading?: T;
                          content?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              resourceSubmenu?:
                | T
                | {
                    linkList?:
                      | T
                      | {
                          icon?: T;
                          title?: T;
                          linkLabel?: T;
                          linkType?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                          id?: T;
                        };
                    articles?:
                      | T
                      | {
                          heading?: T;
                          limit?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  primaryButtonLabel?: T;
  primaryButtonLink?: T;
  secondaryButtonLabel?: T;
  secondaryButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerNavigation?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              linkLabel?: T;
              linkType?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  logo?: T;
  copyrightNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}